"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _mini_package_details_bone_pack from './mini-package-details-bone-pack.bones.json'
import _mini_package_details_cardiac_pack from './mini-package-details-cardiac-pack.bones.json'
import _mini_package_details_diabetic_pack from './mini-package-details-diabetic-pack.bones.json'
import _mini_package_details_fever_pack from './mini-package-details-fever-pack.bones.json'
import _mini_package_details_gut_pack from './mini-package-details-gut-pack.bones.json'
import _mini_package_details_hypertension_pack from './mini-package-details-hypertension-pack.bones.json'
import _mini_package_details_liver_pack from './mini-package-details-liver-pack.bones.json'
import _mini_package_details_obesity_pack from './mini-package-details-obesity-pack.bones.json'
import _mini_package_details_renal_pack from './mini-package-details-renal-pack.bones.json'
import _package_details_diamond from './package-details-diamond.bones.json'
import _package_details_gold from './package-details-gold.bones.json'
import _package_details_platinum from './package-details-platinum.bones.json'
import _package_details_signature from './package-details-signature.bones.json'
import _package_details_silver from './package-details-silver.bones.json'

registerBones({
  "mini-package-details-bone-pack": _mini_package_details_bone_pack,
  "mini-package-details-cardiac-pack": _mini_package_details_cardiac_pack,
  "mini-package-details-diabetic-pack": _mini_package_details_diabetic_pack,
  "mini-package-details-fever-pack": _mini_package_details_fever_pack,
  "mini-package-details-gut-pack": _mini_package_details_gut_pack,
  "mini-package-details-hypertension-pack": _mini_package_details_hypertension_pack,
  "mini-package-details-liver-pack": _mini_package_details_liver_pack,
  "mini-package-details-obesity-pack": _mini_package_details_obesity_pack,
  "mini-package-details-renal-pack": _mini_package_details_renal_pack,
  "package-details-diamond": _package_details_diamond,
  "package-details-gold": _package_details_gold,
  "package-details-platinum": _package_details_platinum,
  "package-details-signature": _package_details_signature,
  "package-details-silver": _package_details_silver,
})
