/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as AdminBookingsRouteImport } from './routes/_admin/bookings'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminPatientsRouteImport } from './routes/_admin/patients'
import { Route as AdminPrescriptionsRouteImport } from './routes/_admin/prescriptions'
import { Route as AdminSubscribersRouteImport } from './routes/_admin/subscribers'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as ProtectedBookingRouteImport } from './routes/_protected/booking'
import { Route as ProtectedCartRouteImport } from './routes/_protected/cart'
import { Route as ProtectedPaymentSuccessRouteImport } from './routes/_protected/payment-success'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as PackagesIndexRouteImport } from './routes/packages/index'
import { Route as PackagesPackageRouteImport } from './routes/packages/$package'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPaymentCallbackRouteImport } from './routes/api/payment/callback'
import { Route as ApiPaymentCheckoutRouteImport } from './routes/api/payment/checkout'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as BlogsBlogIdIndexRouteImport } from './routes/blogs/$blogId/index'
import { Route as PackagesMiniPackagesMiniPackageRouteImport } from './routes/packages/mini-packages/$miniPackage'

const PrivacyPolicyLazyRouteImport = createFileRoute('/privacy-policy')()
const RefundPolicyLazyRouteImport = createFileRoute('/refund-policy')()
const TermsAndConditionLazyRouteImport = createFileRoute(
  '/terms-and-condition',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyLazyRoute = PrivacyPolicyLazyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/privacy-policy.lazy').then((d) => d.Route),
)
const RefundPolicyLazyRoute = RefundPolicyLazyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/refund-policy.lazy').then((d) => d.Route))
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionLazyRoute = TermsAndConditionLazyRouteImport.update({
  id: '/terms-and-condition',
  path: '/terms-and-condition',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/terms-and-condition.lazy').then((d) => d.Route),
)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrescriptionsRoute = AdminPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedBookingRoute = ProtectedBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCartRoute = ProtectedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPaymentSuccessRoute = ProtectedPaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesPackageRoute = PackagesPackageRouteImport.update({
  id: '/packages/$package',
  path: '/packages/$package',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCallbackRoute = ApiPaymentCallbackRouteImport.update({
  id: '/api/payment/callback',
  path: '/api/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCheckoutRoute = ApiPaymentCheckoutRouteImport.update({
  id: '/api/payment/checkout',
  path: '/api/payment/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogIdIndexRoute = BlogsBlogIdIndexRouteImport.update({
  id: '/blogs/$blogId/',
  path: '/blogs/$blogId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesMiniPackagesMiniPackageRoute =
  PackagesMiniPackagesMiniPackageRouteImport.update({
    id: '/packages/mini-packages/$miniPackage',
    path: '/packages/mini-packages/$miniPackage',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tests': typeof TestsRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/refund-policy': typeof RefundPolicyLazyRoute
  '/terms-and-condition': typeof TermsAndConditionLazyRoute
  '/bookings': typeof AdminBookingsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/patients': typeof AdminPatientsRoute
  '/prescriptions': typeof AdminPrescriptionsRoute
  '/subscribers': typeof AdminSubscribersRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/booking': typeof ProtectedBookingRoute
  '/cart': typeof ProtectedCartRoute
  '/payment-success': typeof ProtectedPaymentSuccessRoute
  '/profile': typeof ProtectedProfileRoute
  '/packages/$package': typeof PackagesPackageRoute
  '/blogs/': typeof BlogsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/packages/mini-packages/$miniPackage': typeof PackagesMiniPackagesMiniPackageRoute
  '/blogs/$blogId/': typeof BlogsBlogIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tests': typeof TestsRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/refund-policy': typeof RefundPolicyLazyRoute
  '/terms-and-condition': typeof TermsAndConditionLazyRoute
  '/bookings': typeof AdminBookingsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/patients': typeof AdminPatientsRoute
  '/prescriptions': typeof AdminPrescriptionsRoute
  '/subscribers': typeof AdminSubscribersRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/booking': typeof ProtectedBookingRoute
  '/cart': typeof ProtectedCartRoute
  '/payment-success': typeof ProtectedPaymentSuccessRoute
  '/profile': typeof ProtectedProfileRoute
  '/packages/$package': typeof PackagesPackageRoute
  '/blogs': typeof BlogsIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/packages/mini-packages/$miniPackage': typeof PackagesMiniPackagesMiniPackageRoute
  '/blogs/$blogId': typeof BlogsBlogIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tests': typeof TestsRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/refund-policy': typeof RefundPolicyLazyRoute
  '/terms-and-condition': typeof TermsAndConditionLazyRoute
  '/_admin/bookings': typeof AdminBookingsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/patients': typeof AdminPatientsRoute
  '/_admin/prescriptions': typeof AdminPrescriptionsRoute
  '/_admin/subscribers': typeof AdminSubscribersRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_protected/booking': typeof ProtectedBookingRoute
  '/_protected/cart': typeof ProtectedCartRoute
  '/_protected/payment-success': typeof ProtectedPaymentSuccessRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/packages/$package': typeof PackagesPackageRoute
  '/blogs/': typeof BlogsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/packages/mini-packages/$miniPackage': typeof PackagesMiniPackagesMiniPackageRoute
  '/blogs/$blogId/': typeof BlogsBlogIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact-us'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tests'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-condition'
    | '/bookings'
    | '/dashboard'
    | '/patients'
    | '/prescriptions'
    | '/subscribers'
    | '/login'
    | '/register'
    | '/booking'
    | '/cart'
    | '/payment-success'
    | '/profile'
    | '/packages/$package'
    | '/blogs/'
    | '/packages/'
    | '/api/auth/$'
    | '/api/payment/callback'
    | '/api/payment/checkout'
    | '/api/trpc/$'
    | '/packages/mini-packages/$miniPackage'
    | '/blogs/$blogId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact-us'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tests'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-condition'
    | '/bookings'
    | '/dashboard'
    | '/patients'
    | '/prescriptions'
    | '/subscribers'
    | '/login'
    | '/register'
    | '/booking'
    | '/cart'
    | '/payment-success'
    | '/profile'
    | '/packages/$package'
    | '/blogs'
    | '/packages'
    | '/api/auth/$'
    | '/api/payment/callback'
    | '/api/payment/checkout'
    | '/api/trpc/$'
    | '/packages/mini-packages/$miniPackage'
    | '/blogs/$blogId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_protected'
    | '/contact-us'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tests'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-condition'
    | '/_admin/bookings'
    | '/_admin/dashboard'
    | '/_admin/patients'
    | '/_admin/prescriptions'
    | '/_admin/subscribers'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/booking'
    | '/_protected/cart'
    | '/_protected/payment-success'
    | '/_protected/profile'
    | '/packages/$package'
    | '/blogs/'
    | '/packages/'
    | '/api/auth/$'
    | '/api/payment/callback'
    | '/api/payment/checkout'
    | '/api/trpc/$'
    | '/packages/mini-packages/$miniPackage'
    | '/blogs/$blogId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ContactUsRoute: typeof ContactUsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestsRoute: typeof TestsRoute
  PrivacyPolicyLazyRoute: typeof PrivacyPolicyLazyRoute
  RefundPolicyLazyRoute: typeof RefundPolicyLazyRoute
  TermsAndConditionLazyRoute: typeof TermsAndConditionLazyRoute
  PackagesPackageRoute: typeof PackagesPackageRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymentCallbackRoute: typeof ApiPaymentCallbackRoute
  ApiPaymentCheckoutRoute: typeof ApiPaymentCheckoutRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  PackagesMiniPackagesMiniPackageRoute: typeof PackagesMiniPackagesMiniPackageRoute
  BlogsBlogIdIndexRoute: typeof BlogsBlogIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-condition': {
      id: '/terms-and-condition'
      path: '/terms-and-condition'
      fullPath: '/terms-and-condition'
      preLoaderRoute: typeof TermsAndConditionLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/bookings': {
      id: '/_admin/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/patients': {
      id: '/_admin/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/prescriptions': {
      id: '/_admin/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AdminPrescriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/subscribers': {
      id: '/_admin/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/booking': {
      id: '/_protected/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof ProtectedBookingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/cart': {
      id: '/_protected/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ProtectedCartRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/payment-success': {
      id: '/_protected/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof ProtectedPaymentSuccessRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$package': {
      id: '/packages/$package'
      path: '/packages/$package'
      fullPath: '/packages/$package'
      preLoaderRoute: typeof PackagesPackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/callback': {
      id: '/api/payment/callback'
      path: '/api/payment/callback'
      fullPath: '/api/payment/callback'
      preLoaderRoute: typeof ApiPaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/checkout': {
      id: '/api/payment/checkout'
      path: '/api/payment/checkout'
      fullPath: '/api/payment/checkout'
      preLoaderRoute: typeof ApiPaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$blogId/': {
      id: '/blogs/$blogId/'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId/'
      preLoaderRoute: typeof BlogsBlogIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/mini-packages/$miniPackage': {
      id: '/packages/mini-packages/$miniPackage'
      path: '/packages/mini-packages/$miniPackage'
      fullPath: '/packages/mini-packages/$miniPackage'
      preLoaderRoute: typeof PackagesMiniPackagesMiniPackageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminPrescriptionsRoute: typeof AdminPrescriptionsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminPrescriptionsRoute: AdminPrescriptionsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedBookingRoute: typeof ProtectedBookingRoute
  ProtectedCartRoute: typeof ProtectedCartRoute
  ProtectedPaymentSuccessRoute: typeof ProtectedPaymentSuccessRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBookingRoute: ProtectedBookingRoute,
  ProtectedCartRoute: ProtectedCartRoute,
  ProtectedPaymentSuccessRoute: ProtectedPaymentSuccessRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ContactUsRoute: ContactUsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestsRoute: TestsRoute,
  PrivacyPolicyLazyRoute: PrivacyPolicyLazyRoute,
  RefundPolicyLazyRoute: RefundPolicyLazyRoute,
  TermsAndConditionLazyRoute: TermsAndConditionLazyRoute,
  PackagesPackageRoute: PackagesPackageRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymentCallbackRoute: ApiPaymentCallbackRoute,
  ApiPaymentCheckoutRoute: ApiPaymentCheckoutRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  PackagesMiniPackagesMiniPackageRoute: PackagesMiniPackagesMiniPackageRoute,
  BlogsBlogIdIndexRoute: BlogsBlogIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
